//LOCALHOST
### the request above returns a json object with contact data for someone. No database is connected.
GET HTTP://localhost:`{$port}`/contact
#Contact: Devin
GET http://localhost:8080/contact/6518d2947c63fc6145c181b0
#Contact: Ashley
GET http://localhost:8080/contact/6518d29d7c63fc6145c181b1
#Contact: Joshua
GET http://localhost:8080/contact/6518d2077c63fc6145c181ae